#! /usr/bin/env bash

export BASE="$(dirname $PWD/$0)"
export ENV_PATH="$BASE/env"

export TOOL_PATH="$BASE/tools"

export PY_ENV="$BASE/.py"
export PYLIB_PATH="$PY_ENV/lib/python2.7/site-packages"

export ENV_ETC_PATH="$ENV_PATH/etc"
export ENV_RUN_PATH="$ENV_PATH/var/run"
export ENV_LOG_PATH="$ENV_PATH/var/log"

export NGINX_CONFIG_PATH="$ENV_ETC_PATH/nginx"

# !!! DONT'T START WITH UWSGI !!! (...after 1.9.5)
export _UWSGI_VASSAL_PATH="$ENV_ETC_PATH/uwsgi/vassals"
export _UWSGI_DESC='Avalon'
export _UWSGI_NAME='avalon'

if [ -n "${AVALON_ENVIRON}" ]; then
    return
fi
if [ -n "$(echo $HOSTNAME | grep gkserver)" ]; then
    export AVALON_ENVIRON="PRODUCTION"
elif [ -n "$(echo $HOSTNAME | grep qaserver)" ]; then
    export AVALON_ENVIRON="STAGING"
else
    export AVALON_ENVIRON="DEVELOPMENT"
fi

if [ ! -d $PY_ENV ]; then
    virtualenv $PY_ENV
fi

mkdir -p $ENV_ETC_PATH
mkdir -p $ENV_LOG_PATH
mkdir -p $ENV_RUN_PATH
mkdir -p $NGINX_CONFIG_PATH
mkdir -p $_UWSGI_VASSAL_PATH

echo "BASE: $BASE"
echo "PYTHON ENVIRONMENT: $PY_ENV"
echo "TOOL_PATN: $TOOL_PATH"
echo $AVALON_ENVIRON
echo

source $PY_ENV/bin/activate
sh $TOOL_PATH/init
source $TOOL_PATH/functions.sh
