#! /usr/bin/env bash

pip install bottle
pip install sqlalchemy
pip install beaker
pip install jinja2
pip install markdown2
pip install pyyaml
pip install pygments
pip install ipython
pip install alembic
pip install psycopg2
pip install python-memcached 
pip install uwsgi
pip install pep8
pip install pyflakes
pip install pylint
pip install autopep8
pip install wtforms 
pip install simplejson
pip install requests
pip install voluptuous

ln -s -f -n $BASE/share/share-python $PYLIB_PATH/share
