#! /usr/bin/env bash

pip install bottle
pip install sqlalchemy
pip install beaker
pip install jinja2
pip install markdown2
pip install pyyaml
pip install pygments
pip install ipython
pip install mysql-python
pip install alembic
pip install uwsgi
pip install python-memcached 

ln -s -f -n $BASE/share/share-python $PYLIB_PATH/share
